import Head from 'next/head';
import React from 'react';
import Card from '../components/Card';
import Content from '../components/Content';
import Footer from '../components/Footer';
import Info from '../components/Info';
import Navbar from '../components/Navbar';


export default function Home({data}) {

  const spacexdata = data;

const count = 0

  return (
    <div>
        <Head>
          HEAD
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar/>
        <Content/>

       <div className="cards">
       {spacexdata.map(data => (
              <Card  key={data.flight_number} spacexdata={data}/>
          ))}
       </div>

       <Info/>
          
        <Footer/>
    </div>
  )
}


export const getStaticProps = async () => {
  
  const res = await fetch("https://api.spacexdata.com/v3/launches/past");
  const data = await res.json();

  return {
    props: {
      data
    }
  }
}
